### ISSUE TITLE
Changing the value of NODE_ENV can break builds

### ISSUE THREAD

**Issue by BenoitAverty** [architect/functions#383]
**Describe the issue**
In index.js of this module, there is an assignment of the value `"testing"` to the variable `process.env.NODE_ENV`. However, many people consider env vars to be constants, and some build tools (like rollup's `@rollup/plugin-replace` plugin) will replace the variable by it's value, resulting in a parse error.

**Steps` to reproduce**
I've had the problem using remix.run, however it should be reproductible with any project witht the same plugin.

1. Make a module that imports @architect/functions
2. build the module using @rollup/plugin-replace to replace the process.env.NODE_ENV value to "development" 

**Expected behavior**
the project builds

**Additional context**

One "solution" is to configure the plugin with the `preventAssignment` parameter, but then the process.env.NODE_ENV variable would keep the "development" value, which seems to not be a correct value for @architect/functions.

**Comment by brianleroux** [comment]
So, there are a few things to touch on here. Env vars are very common for switching logic _at runtime_. `NODE_ENV` is used by `architect/functions` because the only place you can run `architect/functions` is Node…again at runtime. This is a very old pattern. Older than frontend bundlers using `NODE_ENV`. I do regret not namespacing to `ARC_ENV`. I had assumed that was safe because it was a pretty standard practice. Sometime somewhat recently bundlers started using NODE_ENV at author time for targeting a web browser at runtime. I wish they opted to make that a CLI flag, like it should be, but here we are. 

I'm glad you found a workaround solution for your bundler. Another solution worth considering is you probably do not have to bundle your Node runtime code. There should be no need to! Performance is often cited but if you can keep your payloads below 5mb you will have sub second cold starts. That is a lot of code! It is also worth considering that bundling really hurts your ability to debug code at runtime. Stack traces with line numbers are key to fast issue resolution…you usually lose that when you bundle which isn't a great tradeoff.

That said sometimes folks NEED to bundle and that's cool too! I am open to a PR that changes all references to `NODE_ENV` to `ARC_ENV`. This would be a major bump for us to merge however.

**Comment by BenoitAverty** [comment]
Yeah I thought about it and I mostly agree with you... Even while bundling, the replacement plugin is not mandatory I think.

I'm using Remix, so I don't have the possibility to change the build process, but I'll point them at this issue.

I still think it's risky to assign to NODE_ENV, I doubt I'll find the time to submit the PR but if I do I'll try to submit it.

**Comment by filmaj** [comment]
Understood. Yeah, if we can't rely on `NODE_ENV` to determine the difference between a local development environment compared to a staging or production environment then we should tackle that issue before we bake that in any further and expose it to third party arc plugin developers!
